name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Configure env file
        run: |
          echo "REACT_APP_API_PROFILE=${{ secrets.REACT_APP_API_PROFILE }}" > .env
          echo "REACT_APP_CHAIN_ID=${{ secrets.REACT_APP_CHAIN_ID }}" >> .env
          echo "REACT_APP_GTAG=${{ secrets.REACT_APP_GTAG }}" >> .env
          echo "REACT_APP_NETWORK_URL=${{ secrets.REACT_APP_NETWORK_URL }}" >> .env
          echo "REACT_APP_ETH_PROVIDER_LINK=${{ secrets.REACT_APP_ETH_PROVIDER_LINK }}" >> .env
          echo "REACT_APP_TREAURY_WALLET_AFFRESS=${{ secrets.REACT_APP_TREAURY_WALLET_AFFRESS }}" >> .env
          echo "REACT_APP_TREAURY_CONTRACT_ADDRESS=${{ secrets.REACT_APP_TREAURY_CONTRACT_ADDRESS }}" >> .env
          echo "SKIP_PREFLIGHT_CHECK=${{ secrets.SKIP_PREFLIGHT_CHECK }}" >> .env
          echo "REACT_APP_CHAIN_NAME=${{ secrets.REACT_APP_CHAIN_NAME }}" >> .env
          echo "REACT_APP_GALAXY_EXCHANGE_URL=http://stage.exchange.galaxyswap.net.s3-website-us-east-1.amazonaws.com" >> .env
          echo "REACT_APP_GALAXY_SWAP_URL=http://stage.frontend.galaxyswap.net.s3-website-us-east-1.amazonaws.com" >> .env
          cat .env
      - name: Build React App
        run: rm -rf build && rm package-lock.json -f && rm yarn.lock -f && npm i && npm run build
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./build/ s3://stage.frontend.galaxyswap.net --delete
